[package]
name = "sounds"
version = "0.6.3"
edition = "2024"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.30.0"
serde_json = "1.0.150"
serde = { version = "1", features = ["derive"] }
rodio = "0.22.2"
lofty = "0.24.0"

[dev-dependencies]
tempfile = "3.27.0"
